### ISSUE TITLE
Loading state_dict error

### ISSUE THREAD

**Issue by charmeleonz** [VincenDen/IID#3]
Dear authors,

I'v followed the commands provided by this repository and run into the following error.

<img width="1238" alt="Screenshot 2024-08-11 at 14 02 17" src="https://github.com/user-attachments/assets/d107b469-f422-4744-910c-403827d03826">

Could you advise what may have caused this? 

Thank you.

**Comment by SunnyBhati** [comment]
Hi , I am facing the same issue. Can you please tell what change you did ?
